site_name: backend-api
repo_url: https://github.com/NanoClem/backend-api
site_url: https://NanoClem.github.io/backend-api
site_description: Backend API for the Feedback product
site_author: NanoClem
edit_uri: edit/main/docs/
repo_name: NanoClem/backend-api
copyright: Maintained by <a href="https://NanoClem.com">NanoClem</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [backend_api]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NanoClem/backend-api
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/backend-api

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
